// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFVageUfKPwsMdHRs3Wb20TMM_UWcSHWw',
    appId: '1:573288688833:web:3a32f9d1d9c87460bef840',
    messagingSenderId: '573288688833',
    projectId: 'cut-spot1',
    authDomain: 'cut-spot1.firebaseapp.com',
    storageBucket: 'cut-spot1.appspot.com',
    measurementId: 'G-ZPVBGN0MPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuiw6__49xqRCOyC8QrPtajsHYQRPqBVU',
    appId: '1:573288688833:android:7c6427965003a4e1bef840',
    messagingSenderId: '573288688833',
    projectId: 'cut-spot1',
    storageBucket: 'cut-spot1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAadVi65DOVlQKAwsK1AYIntC3JT2Qn9DU',
    appId: '1:573288688833:ios:c1eb9f46aa0be2a0bef840',
    messagingSenderId: '573288688833',
    projectId: 'cut-spot1',
    storageBucket: 'cut-spot1.appspot.com',
    iosBundleId: 'com.example.cutSpot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAadVi65DOVlQKAwsK1AYIntC3JT2Qn9DU',
    appId: '1:573288688833:ios:c1eb9f46aa0be2a0bef840',
    messagingSenderId: '573288688833',
    projectId: 'cut-spot1',
    storageBucket: 'cut-spot1.appspot.com',
    iosBundleId: 'com.example.cutSpot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFVageUfKPwsMdHRs3Wb20TMM_UWcSHWw',
    appId: '1:573288688833:web:b7cda351ffcca8b0bef840',
    messagingSenderId: '573288688833',
    projectId: 'cut-spot1',
    authDomain: 'cut-spot1.firebaseapp.com',
    storageBucket: 'cut-spot1.appspot.com',
    measurementId: 'G-L5DPDV9VBZ',
  );
}
